### ISSUE TITLE
Fail to build 

### ISSUE THREAD

**Issue by leannejdong** [Jimmy-Lin/GeneralizedOptimalSparseDecisionTrees#5]
Hi Jimmy, i tried to rebuild your very original project under your developer instruction. 
In step 3, ./autobuild --test
I got error towards the end of the process, i.e.
config.status: creating Makefile
config.status: executing depfiles commands
g++ -std=gnu++11  -O3   -o gosdt_test   -lgmp 
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:681: gosdt_test] Error 1

In step 4, ./autobuild --install --enable-tests
g++ -std=gnu++11  -O3 -Wall -I include -pthread     -o gosdt src/gosdt-bitmask.o src/gosdt-configuration.o src/gosdt-task.o src/gosdt-message.o src/gosdt-tile.o src/gosdt-graph.o src/gosdt-queue.o src/gosdt-model.o src/gosdt-encoder.o src/gosdt-index.o src/gosdt-dataset.o src/gosdt-optimizer.o src/gosdt-state.o src/gosdt-local_state.o src/gosdt-gosdt.o src/gosdt-main.o -ltbb -ltbbmalloc -lgmp  -lgmp 
make[1]: Entering directory '/home/leanne/Dev/GeneralizedOptimalSparseDecisionTrees'
 /usr/bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c gosdt '/usr/local/bin'
/usr/bin/install: cannot remove '/usr/local/bin/gosdt': Permission denied
make[1]: *** [Makefile:558: install-binPROGRAMS] Error 1
make[1]: Leaving directory '/home/leanne/Dev/GeneralizedOptimalSparseDecisionTrees'
make: *** [Makefile:1432: install-am] Error 2

Would you look into them? I'm on ubuntu20.04 with a modern compiler installed. Thanks so much, leanne

**Comment by VibratingPig** [comment]
Leanne,

You need run this this as sudo to allow the script to install the executable under /usr/local/bin otherwise the executable should be under your current directory and can use it by referring it it absolutely:

for example for me I build under /home/VP/Documents/projects/gosdt2 i get the same error **but** the executable is there and is called gosdt.

I can still use the code if I refer to it as /home/VP/Documents/projects/gosdt2/gosdt or ./gosdt from that directory.

Please let me know how you get on.

Regards,

VP

**Comment by leannejdong** [comment]
Hi VP, I understand I sometimes need sudo in this kind of situation, but am afraid that is not quite that. There is a line in the test script needs to be corrected. See error below
g++ -std=gnu++11  -O3   -o gosdt_test   -lgmp 
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:681: gosdt_test] Error 1

You can go through the steps here and let me know how you go...

Thanks, Leanne

**Comment by VibratingPig** [comment]
Leanne,

My apologises I was looking at the deployment error to /usr/local/bin - yes I get the same error. I note that if I run 

./autobuild --reconfigure --enable-tests
and then
./autobuild --test 

it appears to compile, link and run but there are some failures. Maybe @Jimmy-Lin can comment ?

Thanks,

VP

**Comment by leannejdong** [comment]
Hi, As Jimmy mentioned. One can rebuild using the non-developer option, i.e., via
./autobuild --build

Thanks, Leanne
